"""
TOOL-01 gap: verify multi-message proto file grouping behavior.

The explicit composite-proto inventory below must group each file into a single
.audit.yaml sidecar with combined evidence. Tests verify:
- (a) Proto files with multiple mappings produce exactly one sidecar on disk
- (b) Evidence entries from multiple declared messages appear in the sidecar

Uses CarControlMessages.proto as the primary fixture — it has 11 messages in one
proto file and its sidecar was generated by run.py.
"""

from pathlib import Path
import re

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
OAA_ROOT = REPO_ROOT / "oaa"

COMPOSITE_PROTO_FILES = (
    Path("av/AVChannelMediaStatsMessage.proto"),
    Path("carcontrol/CarControlMessages.proto"),
    Path("carcontrol/CarPropertyData.proto"),
    Path("control/CapabilityData.proto"),
    Path("control/ConnectionConfigurationData.proto"),
    Path("control/ControlChannelConfigData.proto"),
    Path("control/InputModelData.proto"),
    Path("control/PhoneCapabilitiesData.proto"),
    Path("control/ServiceDiscoveryResponseMessage.proto"),
    Path("navigation/NavigationChannelConfigData.proto"),
    Path("navigation/NavigationDistanceDisplayData.proto"),
    Path("navigation/NavigationDistanceMessage.proto"),
    Path("navigation/NavigationNotificationMessage.proto"),
    Path("navigation/NavigationTurnEventMessage.proto"),
    Path("phone/PhoneStatusInputMessage.proto"),
    Path("phone/PhoneStatusMessage.proto"),
    Path("radio/RadioMessages.proto"),
    Path("sensor/SensorChannelConfigData.proto"),
    Path("video/AdditionalVideoConfigData.proto"),
    Path("wifi/WifiSetupInfoMessage.proto"),
)


def _declared_messages(proto_path: Path) -> set[str]:
    """Return message names declared by a proto file's current syntax."""
    return set(
        re.findall(
            r"^\s*message\s+(\w+)",
            proto_path.read_text(encoding="utf-8"),
            flags=re.MULTILINE,
        )
    )


def _messages_mentioned_in_evidence(data: dict, declared: set[str]) -> set[str]:
    """Find declared proto messages as exact tokens in evidence string values."""
    tokens = set()

    def collect(value) -> None:
        if isinstance(value, str):
            tokens.update(re.findall(r"[A-Za-z_]\w*", value))
        elif isinstance(value, dict):
            for child in value.values():
                collect(child)
        elif isinstance(value, list):
            for child in value:
                collect(child)

    collect(data.get("evidence") or [])
    return declared & tokens


def test_evidence_message_matching_uses_exact_tokens():
    """A longer declared message name must not imply its prefix message."""
    data = {"evidence": [{"description": "CarControlGroup is handled here"}]}

    assert _messages_mentioned_in_evidence(
        data, {"CarControl", "CarControlGroup"}
    ) == {"CarControlGroup"}


def test_composite_inventory_does_not_depend_on_evidence_coverage(
    tmp_path: Path,
):
    """A declared composite stays inventoried and fails after evidence is lost."""
    package_dir = tmp_path / "example"
    package_dir.mkdir()
    (package_dir / "Composite.proto").write_text(
        'syntax = "proto2";\nmessage First {}\nmessage Second {}\n',
        encoding="utf-8",
    )
    (package_dir / "Composite.audit.yaml").write_text(
        yaml.safe_dump(
            {
                "proto": "example/Composite.proto",
                "message": "Composite (all)",
                "evidence": [{"description": "First only"}],
            }
        ),
        encoding="utf-8",
    )
    inventory = _find_multi_message_protos(
        tmp_path, (Path("example/Composite.proto"),)
    )
    assert inventory == [
        (
            package_dir / "Composite.proto",
            package_dir / "Composite.audit.yaml",
        )
    ]
    with pytest.raises(AssertionError, match="covers only 1 declared message"):
        _assert_composite_evidence_coverage(*inventory[0])


def _find_multi_message_protos(
    root: Path | None = None,
    composite_proto_files: tuple[Path, ...] = COMPOSITE_PROTO_FILES,
) -> list[tuple[Path, Path]]:
    """
    Find proto files whose sidecars explicitly declare composite coverage.

    Returns list of (proto_path, sidecar_path) tuples.
    """
    root = root or OAA_ROOT
    if not root.exists():
        return []

    return [
        (root / proto_path, (root / proto_path).with_suffix(".audit.yaml"))
        for proto_path in composite_proto_files
    ]


def _assert_composite_evidence_coverage(
    proto_path: Path, sidecar_path: Path
) -> None:
    """Require evidence from at least two exact declared message names."""
    with open(sidecar_path, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    mentioned_messages = _messages_mentioned_in_evidence(
        data, _declared_messages(proto_path)
    )
    assert len(mentioned_messages) >= 2, (
        f"{sidecar_path}: composite evidence covers only "
        f"{len(mentioned_messages)} declared message(s): {mentioned_messages}."
    )


MULTI_MESSAGE_SIDECARS = _find_multi_message_protos()


# ---------------------------------------------------------------------------
# Concrete fixture: CarControlMessages.proto (11 messages, well-known case)
# ---------------------------------------------------------------------------

CAR_CONTROL_PROTO = OAA_ROOT / "carcontrol" / "CarControlMessages.proto"
CAR_CONTROL_SIDECAR = OAA_ROOT / "carcontrol" / "CarControlMessages.audit.yaml"

KNOWN_CAR_CONTROL_MESSAGES = [
    "CarActionControl",
    "CarActionNotification",
    "CarControl",
    "CarControlChannelDescriptor",
    "CarControlGroup",
    "CarControlGroupUpdate",
    "CarPropertyChangeEvent",
]


@pytest.mark.skipif(
    not CAR_CONTROL_SIDECAR.exists(),
    reason="CarControlMessages.audit.yaml not found — skipping grouping test",
)
def test_multi_message_proto_produces_exactly_one_sidecar():
    """
    A proto file with multiple message mappings must produce exactly one
    .audit.yaml sidecar (not one per message).

    CarControlMessages.proto has 11 messages and must have exactly one sidecar.
    """
    # Verify there is exactly one sidecar, not per-message sidecars
    carcontrol_dir = OAA_ROOT / "carcontrol"
    sidecars = list(carcontrol_dir.glob("CarControlMessages*.audit.yaml"))
    assert len(sidecars) == 1, (
        f"Expected exactly 1 sidecar for CarControlMessages.proto, "
        f"found {len(sidecars)}: {[s.name for s in sidecars]}. "
        "Multi-message proto files must produce exactly one combined sidecar."
    )
    assert sidecars[0].name == "CarControlMessages.audit.yaml", (
        f"Sidecar must be named 'CarControlMessages.audit.yaml', "
        f"not '{sidecars[0].name}'."
    )


@pytest.mark.skipif(
    not CAR_CONTROL_SIDECAR.exists(),
    reason="CarControlMessages.audit.yaml not found — skipping evidence combination test",
)
def test_multi_message_sidecar_contains_evidence_from_multiple_messages():
    """
    The combined sidecar for a multi-message proto must contain evidence entries
    from all contributing messages — not just the primary one.

    CarControlMessages.audit.yaml must contain evidence describing multiple
    distinct messages (CarActionControl, CarActionNotification, CarControl, etc.).
    """
    with open(CAR_CONTROL_SIDECAR, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    assert data is not None, "CarControlMessages.audit.yaml is empty"
    evidence = data.get("evidence") or []
    assert evidence, "CarControlMessages.audit.yaml must have at least one evidence entry"

    mentioned_messages = _messages_mentioned_in_evidence(
        data, _declared_messages(CAR_CONTROL_PROTO)
    )

    assert len(mentioned_messages) >= 2, (
        f"CarControlMessages.audit.yaml evidence covers only {len(mentioned_messages)} "
        f"message(s): {mentioned_messages}. "
        "Multi-message sidecars must combine evidence from all contributing messages."
    )

    # At least some of the known messages should appear in evidence
    found_known = mentioned_messages & set(KNOWN_CAR_CONTROL_MESSAGES)
    assert len(found_known) >= 2, (
        f"Expected at least 2 of {KNOWN_CAR_CONTROL_MESSAGES} to appear in evidence, "
        f"but only found: {found_known}."
    )


@pytest.mark.skipif(
    not CAR_CONTROL_SIDECAR.exists(),
    reason="CarControlMessages.audit.yaml not found — skipping primary message test",
)
def test_multi_message_sidecar_has_primary_message_field():
    """
    The sidecar's 'message' field must contain the primary message name
    (selected by filename-matching heuristic).
    """
    with open(CAR_CONTROL_SIDECAR, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    primary = data.get("message")
    assert primary is not None, (
        "CarControlMessages.audit.yaml is missing the 'message' field."
    )
    assert isinstance(primary, str) and primary, (
        "The 'message' field must be a non-empty string."
    )
    declared = _declared_messages(CAR_CONTROL_PROTO)
    assert primary in declared or primary == f"{CAR_CONTROL_PROTO.stem} (all)", (
        f"CarControlMessages.audit.yaml primary message '{primary}' is neither a "
        f"declared message nor '{CAR_CONTROL_PROTO.stem} (all)'."
    )


# ---------------------------------------------------------------------------
# Parametric check: all discovered multi-message sidecars
# ---------------------------------------------------------------------------

@pytest.mark.skipif(
    len(MULTI_MESSAGE_SIDECARS) == 0,
    reason="No multi-message sidecars found under oaa/ — skipping parametric grouping check",
)
@pytest.mark.parametrize(
    "proto_path,sidecar_path",
    MULTI_MESSAGE_SIDECARS,
    ids=lambda p: str(p.relative_to(REPO_ROOT)) if hasattr(p, "relative_to") else str(p),
)
def test_each_multi_message_proto_has_single_sidecar(proto_path: Path, sidecar_path: Path):
    """
    For every multi-message proto file: exactly one .audit.yaml sidecar exists
    (not one per message), and the sidecar's 'message' field is populated.
    """
    parent = sidecar_path.parent
    stem = proto_path.stem
    # Check no per-message sidecars exist alongside the combined one
    related = list(parent.glob(f"{stem}*.audit.yaml"))
    assert len(related) == 1, (
        f"{proto_path.relative_to(REPO_ROOT)}: expected exactly 1 combined sidecar, "
        f"found {len(related)}: {[r.name for r in related]}."
    )

    with open(sidecar_path, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    assert data.get("message"), (
        f"{sidecar_path.relative_to(REPO_ROOT)}: 'message' field is empty or missing."
    )

    _assert_composite_evidence_coverage(proto_path, sidecar_path)
