"""
TOOL-01 gap: verify multi-message proto file grouping behavior.

24 proto files contain multiple messages. The import pipeline must group them into
a single .audit.yaml sidecar per proto file with combined evidence. Tests verify:
- (a) Proto files with multiple mappings produce exactly one sidecar on disk
- (b) Evidence entries from all messages appear in the combined sidecar

Uses CarControlMessages.proto as the primary fixture — it has 11 messages in one
proto file and its sidecar was generated by run.py.
"""

from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parents[4]
OAA_ROOT = REPO_ROOT / "oaa"


def _find_multi_message_protos() -> list[tuple[Path, Path]]:
    """
    Find proto files that have audit YAML sidecars with evidence entries
    from more than one message (multi-message grouping indicator).

    Returns list of (proto_path, sidecar_path) tuples.
    """
    if not OAA_ROOT.exists():
        return []

    results = []
    for sidecar in sorted(OAA_ROOT.rglob("*.audit.yaml")):
        with open(sidecar, encoding="utf-8") as fh:
            data = yaml.safe_load(fh)
        if not data:
            continue
        evidence = data.get("evidence") or []
        # Multi-message sidecars have evidence entries describing different messages
        # We can identify them because each apk_static entry's description names
        # a different proto message
        if len(evidence) >= 2:
            described_messages = set()
            for e in evidence:
                desc = e.get("description", "")
                # Description format: "Mapped <MessageName> to obfuscated APK class(es)..."
                if desc.startswith("Mapped "):
                    parts = desc.split(" ")
                    if len(parts) >= 2:
                        described_messages.add(parts[1])
            if len(described_messages) >= 2:
                proto_path = sidecar.with_suffix("").with_suffix(".proto")
                if proto_path.exists():
                    results.append((proto_path, sidecar))

    return results


MULTI_MESSAGE_SIDECARS = _find_multi_message_protos()


# ---------------------------------------------------------------------------
# Concrete fixture: CarControlMessages.proto (11 messages, well-known case)
# ---------------------------------------------------------------------------

CAR_CONTROL_PROTO = OAA_ROOT / "carcontrol" / "CarControlMessages.proto"
CAR_CONTROL_SIDECAR = OAA_ROOT / "carcontrol" / "CarControlMessages.audit.yaml"

KNOWN_CAR_CONTROL_MESSAGES = [
    "CarActionControl",
    "CarActionNotification",
    "CarControl",
    "CarControlChannelDescriptor",
    "CarControlGroup",
    "CarControlGroupUpdate",
    "CarPropertyChangeEvent",
]


@pytest.mark.skipif(
    not CAR_CONTROL_SIDECAR.exists(),
    reason="CarControlMessages.audit.yaml not found — skipping grouping test",
)
def test_multi_message_proto_produces_exactly_one_sidecar():
    """
    A proto file with multiple message mappings must produce exactly one
    .audit.yaml sidecar (not one per message).

    CarControlMessages.proto has 11 messages and must have exactly one sidecar.
    """
    # Verify there is exactly one sidecar, not per-message sidecars
    carcontrol_dir = OAA_ROOT / "carcontrol"
    sidecars = list(carcontrol_dir.glob("CarControlMessages*.audit.yaml"))
    assert len(sidecars) == 1, (
        f"Expected exactly 1 sidecar for CarControlMessages.proto, "
        f"found {len(sidecars)}: {[s.name for s in sidecars]}. "
        "Multi-message proto files must produce exactly one combined sidecar."
    )
    assert sidecars[0].name == "CarControlMessages.audit.yaml", (
        f"Sidecar must be named 'CarControlMessages.audit.yaml', "
        f"not '{sidecars[0].name}'."
    )


@pytest.mark.skipif(
    not CAR_CONTROL_SIDECAR.exists(),
    reason="CarControlMessages.audit.yaml not found — skipping evidence combination test",
)
def test_multi_message_sidecar_contains_evidence_from_multiple_messages():
    """
    The combined sidecar for a multi-message proto must contain evidence entries
    from all contributing messages — not just the primary one.

    CarControlMessages.audit.yaml must contain evidence describing multiple
    distinct messages (CarActionControl, CarActionNotification, CarControl, etc.).
    """
    with open(CAR_CONTROL_SIDECAR, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    assert data is not None, "CarControlMessages.audit.yaml is empty"
    evidence = data.get("evidence") or []
    assert evidence, "CarControlMessages.audit.yaml must have at least one evidence entry"

    # Extract message names referenced in evidence descriptions
    mentioned_messages = set()
    for entry in evidence:
        desc = entry.get("description", "")
        if desc.startswith("Mapped "):
            parts = desc.split(" ")
            if len(parts) >= 2:
                mentioned_messages.add(parts[1])

    assert len(mentioned_messages) >= 2, (
        f"CarControlMessages.audit.yaml evidence covers only {len(mentioned_messages)} "
        f"message(s): {mentioned_messages}. "
        "Multi-message sidecars must combine evidence from all contributing messages."
    )

    # At least some of the known messages should appear in evidence
    found_known = mentioned_messages & set(KNOWN_CAR_CONTROL_MESSAGES)
    assert len(found_known) >= 2, (
        f"Expected at least 2 of {KNOWN_CAR_CONTROL_MESSAGES} to appear in evidence, "
        f"but only found: {found_known}."
    )


@pytest.mark.skipif(
    not CAR_CONTROL_SIDECAR.exists(),
    reason="CarControlMessages.audit.yaml not found — skipping primary message test",
)
def test_multi_message_sidecar_has_primary_message_field():
    """
    The sidecar's 'message' field must contain the primary message name
    (selected by filename-matching heuristic).
    """
    with open(CAR_CONTROL_SIDECAR, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)

    primary = data.get("message")
    assert primary is not None, (
        "CarControlMessages.audit.yaml is missing the 'message' field."
    )
    assert isinstance(primary, str) and primary, (
        "The 'message' field must be a non-empty string."
    )
    # The primary should be one of the known messages in this file
    assert primary in KNOWN_CAR_CONTROL_MESSAGES, (
        f"CarControlMessages.audit.yaml primary message '{primary}' is not one of "
        f"the expected messages: {KNOWN_CAR_CONTROL_MESSAGES}. "
        "The heuristic should pick a message matching the proto filename."
    )


# ---------------------------------------------------------------------------
# Parametric check: all discovered multi-message sidecars
# ---------------------------------------------------------------------------

@pytest.mark.skipif(
    len(MULTI_MESSAGE_SIDECARS) == 0,
    reason="No multi-message sidecars found under oaa/ — skipping parametric grouping check",
)
@pytest.mark.parametrize(
    "proto_path,sidecar_path",
    MULTI_MESSAGE_SIDECARS,
    ids=lambda p: str(p.relative_to(REPO_ROOT)) if hasattr(p, "relative_to") else str(p),
)
def test_each_multi_message_proto_has_single_sidecar(proto_path: Path, sidecar_path: Path):
    """
    For every multi-message proto file: exactly one .audit.yaml sidecar exists
    (not one per message), and the sidecar's 'message' field is populated.
    """
    parent = sidecar_path.parent
    stem = proto_path.stem
    # Check no per-message sidecars exist alongside the combined one
    related = list(parent.glob(f"{stem}*.audit.yaml"))
    assert len(related) == 1, (
        f"{proto_path.relative_to(REPO_ROOT)}: expected exactly 1 combined sidecar, "
        f"found {len(related)}: {[r.name for r in related]}."
    )

    with open(sidecar_path, encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    assert data.get("message"), (
        f"{sidecar_path.relative_to(REPO_ROOT)}: 'message' field is empty or missing."
    )
